---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subastas-deployment
  labels:
    app: subastas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: subastas
  template:
    metadata:
      labels:
        app: subastas
    spec:
      containers:
      - name: subastas
        image: subastas
        imagePullPolicy: "Never"
        ports:
        - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: subastas-service
#   labels:
#     run: subastas
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 3000
#       targetPort: 3000
#       nodePort: 30009
#       protocol: TCP
#   selector:
#     run: subastas
