version: "3"
services: 
  subastas_8080: 
    build: .
    ports: 
      - "8080:8080"
    expose:
      - "8090"
    environment:
      - ADDRESS=tcp://subastas_8080
      - ADDRESSES=tcp://subastas_8081,tcp://subastas_8082,tcp://subastas_8083
    networks:
      - raft
  subastas_8081: 
    build: .
    ports: 
      - "8081:8080"
    expose:
      - "8090"
    environment:
      - ADDRESS=tcp://subastas_8081
      - ADDRESSES=tcp://subastas_8080,tcp://subastas_8082,tcp://subastas_8083
    networks:
      - raft
  subastas_8082: 
    build: .
    ports: 
      - "8082:8080"
    expose:
      - "8090"
    environment:
      - ADDRESS=tcp://subastas_8082
      - ADDRESSES=tcp://subastas_8080,tcp://subastas_8081,tcp://subastas_8083
    networks:
      - raft
  subastas_8083: 
    build: .
    ports: 
      - "8083:8080"
    expose:
      - "8090"
    environment:
      - ADDRESS=tcp://subastas_8083
      - ADDRESSES=tcp://subastas_8080,tcp://subastas_8081,tcp://subastas_8082
    networks:
      - raft
networks:
  raft:
    driver: bridge